package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"time"

	gqlerrors "github.com/kstackhq/kstack/sidecar/graph/errors"
	"github.com/kstackhq/kstack/sidecar/graph/model"
	"github.com/kstackhq/kstack/sidecar/internal/apimeta"
	"github.com/kstackhq/kstack/sidecar/internal/appdb"
	"github.com/kstackhq/kstack/sidecar/internal/auth"
	"github.com/kstackhq/kstack/sidecar/internal/chatsvc"
	"github.com/kstackhq/kstack/sidecar/internal/clustersvc"
	"github.com/kstackhq/kstack/sidecar/internal/llm"
	"github.com/kstackhq/kstack/sidecar/internal/memorysvc"
	"github.com/kstackhq/kstack/sidecar/internal/permissions"
	"github.com/kstackhq/kstack/sidecar/internal/sandbox"
	"github.com/kstackhq/kstack/sidecar/internal/securityconfig"
	"github.com/kstackhq/kstack/sidecar/internal/tools/bash"
)

// Thinking is the resolver for the thinking field: what the message's blocks hold
// of the model's thinking, so the webview reads a summary without learning a
// provider's block shape.
func (r *chatMessageResolver) Thinking(ctx context.Context, obj *chatsvc.ChatMessage) (string, error) {
	return obj.Thinking(), nil
}

// Provider is the resolver for the provider field: the stored id, labelled through
// the llm service. A provider it no longer holds is labelled by its id, with no
// dialect: a message outlives its row. Nil on a user message, which has none.
func (r *chatMessageResolver) Provider(ctx context.Context, obj *chatsvc.ChatMessage) (*model.Provider, error) {
	if obj.ProviderID == "" {
		return nil, nil
	}
	p, ok := r.LLMSvc.Provider(obj.ProviderID)
	if !ok {
		return &model.Provider{ID: obj.ProviderID, Label: obj.ProviderID}, nil
	}
	return &model.Provider{ID: p.ID, Label: p.Label, LlmDialect: &p.Dialect}, nil
}

// FinishedAt is the resolver for the finishedAt field.
func (r *chatMessageResolver) FinishedAt(ctx context.Context, obj *chatsvc.ChatMessage) (*time.Time, error) {
	return nullTime(obj.FinishedAt), nil
}

// ToolCalls is the resolver for the toolCalls field: the list the message carries
// as one JSON string, parsed.
func (r *chatMessageResolver) ToolCalls(ctx context.Context, obj *chatsvc.ChatMessage) ([]*chatsvc.ToolCall, error) {
	return obj.ToolCallList()
}

// Citations is the resolver for the citations field: the list the message
// carries as one JSON string, parsed.
func (r *chatMessageResolver) Citations(ctx context.Context, obj *chatsvc.ChatMessage) ([]*llm.Citation, error) {
	return obj.CitationList()
}

// Caches is the resolver for the caches field — the caches this cluster owns. A
// separate beehive read, so it runs only when selected.
func (r *clusterResolver) Caches(ctx context.Context, obj *clustersvc.Cluster) ([]*clustersvc.ClusterCache, error) {
	return r.ClusterSvc.Caches().ListByCluster(ctx, obj.ID)
}

// Events is the resolver for the events field — this cluster's event timeline. A
// separate beehive read, so it runs only when selected.
func (r *clusterResolver) Events(ctx context.Context, obj *clustersvc.Cluster, category *string, limit *int) ([]*clustersvc.Event, error) {
	evs, err := r.ClusterSvc.Clusters().ListEvents(ctx, obj.ID, category, limit)
	if err != nil {
		return nil, err
	}
	return ptrSlice(evs), nil
}

// Kinds is the resolver for the kinds field — this cache's discovered kind catalog.
// Both ids come off the record, so they cannot name different caches.
func (r *clusterCacheResolver) Kinds(ctx context.Context, obj *clustersvc.ClusterCache) ([]*clustersvc.ClusterCachedDataKind, error) {
	kinds, err := r.ClusterSvc.CachedData().ListKinds(ctx, obj.ClusterID, obj.ID)
	if err != nil {
		return nil, err
	}
	return ptrSlice(kinds), nil
}

// CachedKinds is the resolver for the cachedKinds field — the kinds this cache
// mirrors. Keyed by the cache; the catalog between them is resolved in the service.
func (r *clusterCacheResolver) CachedKinds(ctx context.Context, obj *clustersvc.ClusterCache) ([]*clustersvc.ClusterCachedKind, error) {
	return r.ClusterSvc.CachedKinds().ListByCache(ctx, obj.ID)
}

// Events is the resolver for the events field — this cache's own event timeline.
// A separate beehive read, so it runs only when selected.
func (r *clusterCacheResolver) Events(ctx context.Context, obj *clustersvc.ClusterCache, category *string, limit *int) ([]*clustersvc.Event, error) {
	evs, err := r.ClusterSvc.ListEvents(ctx, obj.ID, category, limit)
	if err != nil {
		return nil, err
	}
	return ptrSlice(evs), nil
}

// Events is the resolver for the events field — this kind's sync-transition
// history. A separate beehive read, so it runs only when selected.
func (r *clusterCachedKindResolver) Events(ctx context.Context, obj *clustersvc.ClusterCachedKind, category *string, limit *int) ([]*clustersvc.Event, error) {
	evs, err := r.ClusterSvc.ListEvents(ctx, obj.ID, category, limit)
	if err != nil {
		return nil, err
	}
	return ptrSlice(evs), nil
}

// SyncEnabled is the resolver for the syncEnabled field: the wire's positive form over the
// stored Paused. The storage field is inverted so a record written before it decodes as
// syncing rather than stopping the fleet on the upgrade; this is the one negation.
func (r *clusterCachedKindSpecResolver) SyncEnabled(ctx context.Context, obj *clustersvc.ClusterCachedKindSpec) (bool, error) {
	return !obj.Paused, nil
}

// Permissions is the resolver for the permissions field — the one live cluster
// call on the Cluster surface, so it runs only when explicitly selected.
// TODO: run a SelfSubjectRulesReview; errors until implemented.
func (r *clusterPrincipalResolver) Permissions(ctx context.Context, obj *clustersvc.ClusterPrincipal, namespace string) (*model.ClusterPermissions, error) {
	return nil, fmt.Errorf("not implemented: permissions")
}

// ClusterEnabledSet is the resolver for the clusterEnabledSet field. The change
// reaches the webview through the cluster watch.
func (r *mutationResolver) ClusterEnabledSet(ctx context.Context, id apimeta.ClusterID, enabled bool) (*clustersvc.Cluster, error) {
	c, err := r.ClusterSvc.Clusters().SetEnabled(ctx, id, enabled)
	return c, clusterErr(err)
}

// ClusterSyncEnabledSet is the resolver for the clusterSyncEnabledSet field.
func (r *mutationResolver) ClusterSyncEnabledSet(ctx context.Context, id apimeta.ClusterID, syncEnabled bool) (*clustersvc.Cluster, error) {
	c, err := r.ClusterSvc.Clusters().SetSyncEnabled(ctx, id, syncEnabled)
	return c, clusterErr(err)
}

// ClusterMonitoringEnabledSet is the resolver for the clusterMonitoringEnabledSet field.
func (r *mutationResolver) ClusterMonitoringEnabledSet(ctx context.Context, id apimeta.ClusterID, monitoringEnabled bool) (*clustersvc.Cluster, error) {
	c, err := r.ClusterSvc.Clusters().SetMonitoringEnabled(ctx, id, monitoringEnabled)
	return c, clusterErr(err)
}

// ClusterConnectionRetry is the resolver for the clusterConnectionRetry field. It
// resolves when the probe it asked for has finished, so the request is held open for
// that long. What the probe found lands on the record's conditions and reaches the
// webview through the cluster watch, not here.
func (r *mutationResolver) ClusterConnectionRetry(ctx context.Context, id apimeta.ClusterID) (bool, error) {
	if err := r.ClusterSvc.RetryConnection(ctx, id); err != nil {
		return false, clusterErr(err)
	}
	return true, nil
}

// ClusterDelete is the resolver for the clusterDelete field. The mark is the whole
// mutation: the mirror tears the runtime down and the chat service sweeps the chats
// behind it, each on its own loop, and the row goes last.
func (r *mutationResolver) ClusterDelete(ctx context.Context, id apimeta.ClusterID) (bool, error) {
	if err := r.ClusterSvc.Clusters().Delete(ctx, id); err != nil {
		return false, clusterErr(err)
	}
	return true, nil
}

// ClusterCacheClear is the resolver for the clusterCacheClear field: delete one cache's
// on-disk file and restart its workers onto the emptied one — nothing else would rebuild
// them. The record stays and re-syncs from scratch. The id is the cache's own.
func (r *mutationResolver) ClusterCacheClear(ctx context.Context, id apimeta.ObjectID) (*clustersvc.ClusterCache, error) {
	return r.ClusterSvc.Caches().Clear(ctx, id)
}

// ClusterCachedKindSyncEnabledSet is the resolver for the clusterCachedKindSyncEnabledSet
// field: stop or resume one kind, keeping its cached rows either way. The id is the
// per-kind record's own.
func (r *mutationResolver) ClusterCachedKindSyncEnabledSet(ctx context.Context, id apimeta.ObjectID, syncEnabled bool) (*clustersvc.ClusterCachedKind, error) {
	return r.ClusterSvc.CachedKinds().SetSyncEnabled(ctx, id, syncEnabled)
}

// ChatSend is the resolver for the chatSend field. The cluster is the chat service's
// to check, inside the send's transaction, so a send and a cluster delete are
// serialized where they meet.
func (r *mutationResolver) ChatSend(ctx context.Context, chatID *apimeta.ChatID, mode chatsvc.Mode, clusterID apimeta.ClusterID, sandboxDisabled bool, networkEnabled bool, networkThisTurn bool, providerID string, modelID string, effort string, requestID string, content string) (*chatsvc.ChatMessage, error) {
	msg, err := r.ChatSvc.Send(ctx, chatID, mode, clusterID, sandboxDisabled, networkEnabled, networkThisTurn, providerID, modelID, effort, requestID, content)
	if err != nil {
		return nil, chatErr(err)
	}
	return &msg, nil
}

// ChatCancel is the resolver for the chatCancel field.
func (r *mutationResolver) ChatCancel(ctx context.Context, chatID apimeta.ChatID) (bool, error) {
	if err := r.ChatSvc.Cancel(ctx, chatID); err != nil {
		return false, chatErr(err)
	}
	return true, nil
}

// ApprovalDecide is the resolver for the approvalDecide field.
func (r *mutationResolver) ApprovalDecide(ctx context.Context, id chatsvc.ApprovalID, decision chatsvc.ApprovalDecision) (bool, error) {
	ok, err := r.ChatSvc.Approve(ctx, id, decision)
	if err != nil {
		return false, approvalErr(err)
	}
	return ok, nil
}

// BackgroundTaskStop is the resolver for the backgroundTaskStop field.
func (r *mutationResolver) BackgroundTaskStop(ctx context.Context, id chatsvc.ToolCallID) (bool, error) {
	ok, err := r.ChatSvc.StopBackgroundTask(ctx, id)
	if err != nil {
		return false, chatErr(err)
	}
	return ok, nil
}

// ChatRename is the resolver for the chatRename field.
func (r *mutationResolver) ChatRename(ctx context.Context, id apimeta.ChatID, title string) (*chatsvc.Chat, error) {
	chat, err := r.ChatSvc.Rename(ctx, id, title)
	if err != nil {
		return nil, chatErr(err)
	}
	return &chat, nil
}

// ChatSandboxDisabledSet is the resolver for the chatSandboxDisabledSet field.
func (r *mutationResolver) ChatSandboxDisabledSet(ctx context.Context, id apimeta.ChatID, sandboxDisabled bool) (*chatsvc.Chat, error) {
	chat, err := r.ChatSvc.SetSandboxDisabled(ctx, id, sandboxDisabled)
	if err != nil {
		return nil, chatErr(err)
	}
	return &chat, nil
}

// ChatNetworkEnabledSet is the resolver for the chatNetworkEnabledSet field.
func (r *mutationResolver) ChatNetworkEnabledSet(ctx context.Context, id apimeta.ChatID, enabled bool) (*chatsvc.Chat, error) {
	chat, err := r.ChatSvc.SetNetworkEnabled(ctx, id, enabled)
	if err != nil {
		return nil, chatErr(err)
	}
	return &chat, nil
}

// ChatDelete is the resolver for the chatDelete field.
func (r *mutationResolver) ChatDelete(ctx context.Context, id apimeta.ChatID) (bool, error) {
	if err := r.ChatSvc.Delete(ctx, id); err != nil {
		return false, chatErr(err)
	}
	return true, nil
}

// SandboxPathInclude is the resolver for the sandboxPathInclude field.
func (r *mutationResolver) SandboxPathInclude(ctx context.Context, dir string, target string) ([]*model.SandboxPathEntry, error) {
	entries, err := r.SecurityCfg.AdoptPath(dir, target)
	return sandboxPathOf(entries), sandboxPathErr(err)
}

// SandboxPathRemove is the resolver for the sandboxPathRemove field.
func (r *mutationResolver) SandboxPathRemove(ctx context.Context, dir string) ([]*model.SandboxPathEntry, error) {
	entries, err := r.SecurityCfg.DropPath(dir)
	return sandboxPathOf(entries), sandboxPathErr(err)
}

// SandboxPathRefresh is the resolver for the sandboxPathRefresh field.
func (r *mutationResolver) SandboxPathRefresh(ctx context.Context) ([]*model.SandboxPathEntry, error) {
	entries, err := r.SecurityCfg.RefreshPath(ctx)
	return sandboxPathOf(entries), sandboxPathErr(err)
}

// SandboxExecutablesProbe is the resolver for the sandboxExecutablesProbe field.
func (r *mutationResolver) SandboxExecutablesProbe(ctx context.Context) ([]*model.SandboxExecutable, error) {
	if !r.probes() {
		return nil, noSandboxExecutables()
	}
	r.Executables.StartProbe(r.registeredExecutables())
	return sandboxExecutablesOf(r.Executables.Report(r.registeredExecutables())), nil
}

// SandboxExecutableRegister is the resolver for the sandboxExecutableRegister field.
func (r *mutationResolver) SandboxExecutableRegister(ctx context.Context, name string, invocation *string) ([]*model.SandboxExecutable, error) {
	if !r.probes() {
		return nil, noSandboxExecutables()
	}
	var given string
	if invocation != nil {
		given = *invocation
	}
	if err := r.SecurityCfg.RegisterExecutable(name, given); err != nil {
		return nil, sandboxExecutableErr(err)
	}
	return sandboxExecutablesOf(r.Executables.Report(r.registeredExecutables())), nil
}

// SandboxExecutableRemove is the resolver for the sandboxExecutableRemove field.
func (r *mutationResolver) SandboxExecutableRemove(ctx context.Context, name string) ([]*model.SandboxExecutable, error) {
	if err := r.SecurityCfg.RemoveExecutable(name); err != nil {
		return nil, sandboxExecutableErr(err)
	}
	if !r.probes() {
		return []*model.SandboxExecutable{}, nil
	}
	return sandboxExecutablesOf(r.Executables.Report(r.registeredExecutables())), nil
}

// MemorySave is the resolver for the memorySave field: an update with an id, a
// create without one.
func (r *mutationResolver) MemorySave(ctx context.Context, input model.MemorySaveInput) (*memorysvc.Memory, error) {
	in := memorysvc.Input{
		ClusterID: input.ClusterID,
		Name:      input.Name,
		Body:      input.Body,
	}
	var (
		m   memorysvc.Memory
		err error
	)
	if input.ID != nil {
		m, err = r.MemorySvc.Update(ctx, *input.ID, in)
	} else {
		m, err = r.MemorySvc.Create(ctx, in)
	}
	if err != nil {
		return nil, memoryErr(err)
	}
	return &m, nil
}

// MemoryDelete is the resolver for the memoryDelete field.
func (r *mutationResolver) MemoryDelete(ctx context.Context, id memorysvc.MemoryID) (bool, error) {
	if err := r.MemorySvc.Delete(ctx, id); err != nil {
		return false, memoryErr(err)
	}
	return true, nil
}

// PermissionDefaultModeSet is the resolver for the permissionDefaultModeSet field.
func (r *mutationResolver) PermissionDefaultModeSet(ctx context.Context, mode permissions.Mode) (*model.PermissionSettings, error) {
	return r.permissionsAfter(ctx, r.SecurityCfg.SetDefaultMode(mode))
}

// PermissionModeSet is the resolver for the permissionModeSet field.
func (r *mutationResolver) PermissionModeSet(ctx context.Context, context string, mode permissions.Mode) (*model.PermissionSettings, error) {
	return r.permissionsAfter(ctx, r.SecurityCfg.SetMode(context, mode))
}

// PermissionModeClear is the resolver for the permissionModeClear field.
func (r *mutationResolver) PermissionModeClear(ctx context.Context, context string) (*model.PermissionSettings, error) {
	return r.permissionsAfter(ctx, r.SecurityCfg.ClearMode(context))
}

// PermissionRuleAdd is the resolver for the permissionRuleAdd field.
func (r *mutationResolver) PermissionRuleAdd(ctx context.Context, input model.PermissionRuleInput) (*model.PermissionSettings, error) {
	rule := permissions.Rule{
		ID: appdb.NewID(), Effect: input.Effect, Class: input.Class,
		Context: input.Context, Namespace: input.Namespace, Verb: input.Verb, Group: input.Group, Kind: input.Kind,
	}
	return r.permissionsAfter(ctx, r.SecurityCfg.AddRule(rule))
}

// PermissionRuleRemove is the resolver for the permissionRuleRemove field.
func (r *mutationResolver) PermissionRuleRemove(ctx context.Context, id string) (*model.PermissionSettings, error) {
	return r.permissionsAfter(ctx, r.SecurityCfg.RemoveRule(id))
}

// ChatGrantRemove is the resolver for the chatGrantRemove field.
func (r *mutationResolver) ChatGrantRemove(ctx context.Context, chatID apimeta.ChatID, id string) ([]*permissions.Rule, error) {
	rules, err := r.ChatSvc.RemoveChatGrant(ctx, chatID, id)
	if err != nil {
		return nil, chatErr(err)
	}
	return rulePointers(rules), nil
}

// PermissionDiscardRefused is the resolver for the permissionDiscardRefused field.
func (r *mutationResolver) PermissionDiscardRefused(ctx context.Context, field string) (*model.PermissionSettings, error) {
	return r.permissionsAfter(ctx, r.SecurityCfg.DiscardRefused(field))
}

// FolderGrant is the resolver for the folderGrant field.
func (r *mutationResolver) FolderGrant(ctx context.Context, chatID *apimeta.ChatID, path string, write bool, duration model.GrantDuration) (*model.SandboxFolders, error) {
	// An always grant belongs to no chat, and a chat's grant names its chat.
	var chat apimeta.ChatID
	if duration == model.GrantDurationChat {
		if chatID == nil || *chatID == "" {
			return nil, gqlerrors.NewValidationError("chatID", "a grant for a chat names the chat")
		}
		chat = *chatID
	}
	if err := r.ChatSvc.GrantFolder(ctx, chat, path, write); err != nil {
		return nil, folderErr(err)
	}
	return r.sandboxFolders(ctx, chat)
}

// FolderRevoke is the resolver for the folderRevoke field.
func (r *mutationResolver) FolderRevoke(ctx context.Context, id string) (*model.SandboxFolders, error) {
	if err := r.ChatSvc.RevokeFolder(id); err != nil {
		return nil, folderErr(err)
	}
	return r.sandboxFolders(ctx, "")
}

// AuthLoginStart is the resolver for the authLoginStart field: setup runs synchronously
// (its error surfaces here), the browser round-trip in the background, with the signed-in
// state arriving via authStateWatch.
func (r *mutationResolver) AuthLoginStart(ctx context.Context) (bool, error) {
	if err := r.Auth.StartLogin(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// AuthLogout is the resolver for the authLogout field: clear locally, broadcast
// signed-out, revoke best-effort.
func (r *mutationResolver) AuthLogout(ctx context.Context) (bool, error) {
	if err := r.Auth.Logout(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// Models is the resolver for the models field.
func (r *queryResolver) Models(ctx context.Context) ([]*model.Model, error) {
	var out []*model.Model
	for _, p := range r.LLMSvc.Providers() {
		provider := &model.Provider{ID: p.ID, Label: p.Label, LlmDialect: &p.Dialect}
		for _, m := range p.Catalog {
			out = append(out, &model.Model{
				Provider: provider, ID: m.ID, Label: m.Label, Efforts: m.Efforts, DefaultEffort: m.DefaultEffort,
			})
		}
	}
	return out, nil
}

// Sandbox is the resolver for the sandbox field.
func (r *queryResolver) Sandbox(ctx context.Context) (*sandbox.Status, error) {
	return &r.Resolver.SandboxStatus, nil
}

// Cluster is the resolver for the cluster field. An id naming nothing is null per the
// schema, not an error; one still being torn down resolves like any other, carrying
// its deletionRequestedAt.
func (r *queryResolver) Cluster(ctx context.Context, id apimeta.ClusterID) (*clustersvc.Cluster, error) {
	return r.ClusterSvc.Clusters().Get(ctx, id)
}

// Clusters is the resolver for the clusters field. Nested objects resolve lazily
// per-selection.
func (r *queryResolver) Clusters(ctx context.Context) ([]*clustersvc.Cluster, error) {
	return r.ClusterSvc.Clusters().List(ctx)
}

// ClusterCache is the resolver for the clusterCache field. An id naming nothing is
// null per the schema, not an error.
func (r *queryResolver) ClusterCache(ctx context.Context, id apimeta.ObjectID) (*clustersvc.ClusterCache, error) {
	return r.ClusterSvc.Caches().Get(ctx, id)
}

// ClusterCaches is the resolver for the clusterCaches field — every cache, or one
// cluster's when scoped. A nil clusterID is the unscoped read, not a missing argument.
func (r *queryResolver) ClusterCaches(ctx context.Context, clusterID *apimeta.ClusterID) ([]*clustersvc.ClusterCache, error) {
	if clusterID != nil {
		return r.ClusterSvc.Caches().ListByCluster(ctx, *clusterID)
	}
	return r.ClusterSvc.Caches().List(ctx)
}

// ClusterCachedKind is the resolver for the clusterCachedKind field. An id
// naming nothing is null per the schema, not an error.
func (r *queryResolver) ClusterCachedKind(ctx context.Context, id apimeta.ObjectID) (*clustersvc.ClusterCachedKind, error) {
	return r.ClusterSvc.CachedKinds().Get(ctx, id)
}

// ClusterCachedKinds is the resolver for the clusterCachedKinds field — every
// per-kind record, or one cache's when scoped.
func (r *queryResolver) ClusterCachedKinds(ctx context.Context, cacheID *apimeta.ObjectID) ([]*clustersvc.ClusterCachedKind, error) {
	if cacheID != nil {
		return r.ClusterSvc.CachedKinds().ListByCache(ctx, *cacheID)
	}
	return r.ClusterSvc.CachedKinds().List(ctx)
}

// SecurityRefused is the resolver for the securityRefused field.
func (r *queryResolver) SecurityRefused(ctx context.Context) ([]*securityconfig.Refusal, error) {
	refused := r.SecurityCfg.Refused()
	out := make([]*securityconfig.Refusal, len(refused))
	for i := range refused {
		out[i] = &refused[i]
	}
	return out, nil
}

// SandboxPath is the resolver for the sandboxPath field.
func (r *queryResolver) SandboxPath(ctx context.Context) ([]*model.SandboxPathEntry, error) {
	return sandboxPathOf(r.SecurityCfg.Path()), nil
}

// SandboxPathFault is the resolver for the sandboxPathFault field.
func (r *queryResolver) SandboxPathFault(ctx context.Context) (*string, error) {
	if fault := r.SecurityCfg.PathFault(); fault != "" {
		return &fault, nil
	}
	return nil, nil
}

// SandboxPathResolved is the resolver for the sandboxPathResolved field.
func (r *queryResolver) SandboxPathResolved(ctx context.Context) (bool, error) {
	return r.SecurityCfg.PathResolved(), nil
}

// SandboxExecutables is the resolver for the sandboxExecutables field.
func (r *queryResolver) SandboxExecutables(ctx context.Context) ([]*model.SandboxExecutable, error) {
	if !r.probes() {
		return []*model.SandboxExecutable{}, nil
	}
	return sandboxExecutablesOf(r.Executables.Report(r.registeredExecutables())), nil
}

// PermissionSettings is the resolver for the permissionSettings field.
func (r *queryResolver) PermissionSettings(ctx context.Context) (*model.PermissionSettings, error) {
	return r.permissionSettings(ctx)
}

// SandboxFolders is the resolver for the sandboxFolders field.
func (r *queryResolver) SandboxFolders(ctx context.Context, chatID *apimeta.ChatID) (*model.SandboxFolders, error) {
	var chat apimeta.ChatID
	if chatID != nil {
		chat = *chatID
	}
	return r.sandboxFolders(ctx, chat)
}

// ChatGrants is the resolver for the chatGrants field.
func (r *queryResolver) ChatGrants(ctx context.Context, chatID apimeta.ChatID) ([]*permissions.Rule, error) {
	rules, err := r.ChatSvc.ChatGrants(ctx, chatID)
	if err != nil {
		return nil, chatErr(err)
	}
	return rulePointers(rules), nil
}

// AuthState is the resolver for the authState field. auth.State binds directly to the
// GraphQL type, so only schema fields are exposed — State.Tokens never reaches the wire.
func (r *queryResolver) AuthState(ctx context.Context) (*auth.State, error) {
	state, err := r.Auth.Current(ctx)
	if err != nil {
		return nil, err
	}
	return &state, nil
}

// EventsWatch is the resolver for the eventsWatch field — the live event tail for any
// record with a timeline, decoupled from that record's own watch.
func (r *subscriptionResolver) EventsWatch(ctx context.Context, id apimeta.ObjectID, category *string) (<-chan *clustersvc.EventWatchFrame, error) {
	st, err := r.ClusterSvc.WatchEvents(ctx, id, category)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, st.Frames, st.Err), nil
}

// ClustersWatch is the resolver for the clustersWatch field — the cluster list as
// a delta watch (Added snapshot, then per-cluster Added/Modified/Deleted). Cache
// sync status rides clusterCachesWatch, joined client-side.
func (r *subscriptionResolver) ClustersWatch(ctx context.Context) (<-chan *clustersvc.ClusterWatchFrame, error) {
	st, err := r.ClusterSvc.Clusters().WatchList(ctx)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, st.Frames, st.Err), nil
}

// ClusterEventsWatch is the resolver for the clusterEventsWatch field — the cluster's
// own event tail, the same shape as EventsWatch under the cluster's id.
func (r *subscriptionResolver) ClusterEventsWatch(ctx context.Context, id apimeta.ClusterID, category *string) (<-chan *clustersvc.EventWatchFrame, error) {
	st, err := r.ClusterSvc.Clusters().WatchEvents(ctx, id, category)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, st.Frames, st.Err), nil
}

// ClusterScheduleWatch is the resolver for the clusterScheduleWatch field — the
// live reconcile-schedule gauge for one cluster (next-attempt countdown),
// decoupled from clustersWatch.
func (r *subscriptionResolver) ClusterScheduleWatch(ctx context.Context, id apimeta.ClusterID) (<-chan *clustersvc.Schedule, error) {
	ch, err := r.ClusterSvc.Clusters().WatchSchedule(ctx, id)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterCachesWatch is the resolver for the clusterCachesWatch field — cache
// records as a delta watch parallel to clustersWatch, joined to clusters
// client-side by clusterID.
func (r *subscriptionResolver) ClusterCachesWatch(ctx context.Context) (<-chan *clustersvc.ClusterCacheWatchFrame, error) {
	st, err := r.ClusterSvc.Caches().WatchList(ctx)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, st.Frames, st.Err), nil
}

// ClusterCacheHealthWatch is the resolver for the clusterCacheHealthWatch field.
func (r *subscriptionResolver) ClusterCacheHealthWatch(ctx context.Context) (<-chan *clustersvc.ClusterCacheHealth, error) {
	st, err := r.ClusterSvc.Caches().WatchHealth(ctx)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, st.Frames, st.Err), nil
}

// ClusterCachedKindsWatch is the resolver for the clusterCachedKindsWatch field —
// one cache's per-kind sync records as a delta watch. Cache-scoped, unlike the sibling
// object watches: there is one record per synced kind.
func (r *subscriptionResolver) ClusterCachedKindsWatch(ctx context.Context, cacheID apimeta.ObjectID) (<-chan *clustersvc.ClusterCachedKindWatchFrame, error) {
	st, err := r.ClusterSvc.CachedKinds().WatchByCache(ctx, cacheID)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, st.Frames, st.Err), nil
}

// ClusterCacheStatsWatch is the resolver for the clusterCacheStatsWatch field — one
// cache's contents as a live gauge, streamed because the ClusterCache.stats field freezes
// once its record stops changing.
func (r *subscriptionResolver) ClusterCacheStatsWatch(ctx context.Context, id apimeta.ClusterID, cacheID apimeta.ObjectID) (<-chan *clustersvc.ClusterCacheStats, error) {
	stream, err := r.ClusterSvc.Caches().WatchStats(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, stream.Frames, stream.Err), nil
}

// ClusterCacheSyncStatusWatch is the resolver for the clusterCacheSyncStatusWatch field —
// one cache's sync detail as a gauge. The only thing on the wire carrying a per-kind verdict.
func (r *subscriptionResolver) ClusterCacheSyncStatusWatch(ctx context.Context, id apimeta.ClusterID, cacheID apimeta.ObjectID) (<-chan *clustersvc.ClusterCacheSyncStatus, error) {
	stream, err := r.ClusterSvc.Caches().WatchSyncStatus(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, stream.Frames, stream.Err), nil
}

// ClusterCachedDataKindsWatch is the resolver for the clusterCachedDataKindsWatch field — one
// ClusterCache's kind catalog as a delta watch (the live counterpart of
// clusterCachedDataKinds), so the dashboard nav's kinds + counts track the cluster in
// real time.
func (r *subscriptionResolver) ClusterCachedDataKindsWatch(ctx context.Context, id apimeta.ClusterID, cacheID apimeta.ObjectID) (<-chan *clustersvc.ClusterCachedDataKindWatchFrame, error) {
	stream, err := r.ClusterSvc.CachedData().WatchKinds(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, stream.Frames, stream.Err), nil
}

// ClusterCachedDataEventsWatch is the resolver for the clusterCachedDataEventsWatch field — one
// ClusterCache's cached Kubernetes Events as a delta watch, backing the dashboard's
// events table.
func (r *subscriptionResolver) ClusterCachedDataEventsWatch(ctx context.Context, id apimeta.ClusterID, cacheID apimeta.ObjectID) (<-chan *clustersvc.ClusterCachedDataEventWatchFrame, error) {
	stream, err := r.ClusterSvc.CachedData().WatchEvents(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, stream.Frames, stream.Err), nil
}

// ClusterCachedDataObjectsWatch is the resolver for the clusterCachedDataObjectsWatch field — one
// kind's cached objects as a delta watch, backing the dashboard's per-kind tables.
func (r *subscriptionResolver) ClusterCachedDataObjectsWatch(ctx context.Context, id apimeta.ClusterID, cacheID apimeta.ObjectID, apiVersion string, resource string) (<-chan *clustersvc.ClusterCachedDataObjectWatchFrame, error) {
	stream, err := r.ClusterSvc.CachedData().WatchObjects(ctx, id, cacheID, apiVersion, resource)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, stream.Frames, stream.Err), nil
}

// ChatsWatch is the resolver for the chatsWatch field.
func (r *subscriptionResolver) ChatsWatch(ctx context.Context) (<-chan *chatsvc.ChatWatchFrame, error) {
	st, err := r.ChatSvc.WatchList(ctx)
	if err != nil {
		return nil, chatErr(err)
	}
	return watchStream(ctx, st.Frames, st.Err), nil
}

// ChatMessagesWatch is the resolver for the chatMessagesWatch field.
func (r *subscriptionResolver) ChatMessagesWatch(ctx context.Context, chatID apimeta.ChatID) (<-chan *chatsvc.ChatMessageWatchFrame, error) {
	st, err := r.ChatSvc.WatchMessages(ctx, chatID)
	if err != nil {
		return nil, chatErr(err)
	}
	return watchStream(ctx, st.Frames, st.Err), nil
}

// MemoriesWatch is the resolver for the memoriesWatch field.
func (r *subscriptionResolver) MemoriesWatch(ctx context.Context, clusterID apimeta.ClusterID) (<-chan *memorysvc.MemoryWatchFrame, error) {
	st, err := r.MemorySvc.Watch(ctx, clusterID)
	if err != nil {
		return nil, memoryErr(err)
	}
	return watchStream(ctx, st.Frames, st.Err), nil
}

// SandboxExecutablesWatch is the resolver for the sandboxExecutablesWatch field: the
// probe's state and the settings' registered tools, each a current-on-subscribe
// receiver, folded into one report on either's change. A machine with no
// sandbox answers one empty report.
func (r *subscriptionResolver) SandboxExecutablesWatch(ctx context.Context) (<-chan *model.SandboxExecutablesReport, error) {
	out := make(chan *model.SandboxExecutablesReport)
	send := func(report *model.SandboxExecutablesReport) bool {
		select {
		case out <- report:
			return true
		case <-ctx.Done():
			return false
		}
	}
	if !r.probes() {
		go func() {
			defer close(out)
			send(&model.SandboxExecutablesReport{Executables: []*model.SandboxExecutable{}})
			<-ctx.Done()
		}()
		return out, nil
	}
	probe, settings := r.Executables.WatchProbe(), r.SecurityCfg.Subscribe()
	go func() {
		defer close(out)
		defer probe.Close()
		defer settings.Close()
		var state bash.ProbeState
		registered := r.registeredExecutables()
		probeC, settingsC := probe.Chan(), settings.Chan()
		for {
			select {
			case <-ctx.Done():
				return
			case st, ok := <-probeC:
				if !ok {
					return
				}
				state = st
			case s, ok := <-settingsC:
				if !ok {
					return
				}
				registered = s.Executables
			}
			report := &model.SandboxExecutablesReport{Probing: state.Probing, Probes: state.Probes, Executables: sandboxExecutablesOf(bash.ReportOver(state.Last, registered))}
			if !send(report) {
				return
			}
		}
	}()
	return out, nil
}

// AuthStateWatch is the resolver for the authStateWatch field; the stream is
// current-on-subscribe, so its first value IS the snapshot.
func (r *subscriptionResolver) AuthStateWatch(ctx context.Context) (<-chan *auth.State, error) {
	states, cancel := r.Auth.Subscribe()
	return mapStream(ctx, states, cancel, func(s auth.State) *auth.State { return &s }), nil
}

// Status is the resolver for the status field: null for a call the provider
// ran, which the record keeps as "".
func (r *toolCallResolver) Status(ctx context.Context, obj *chatsvc.ToolCall) (*chatsvc.ToolCallStatus, error) {
	if obj.Status == "" {
		return nil, nil
	}
	return &obj.Status, nil
}

// ChatMessage returns ChatMessageResolver implementation.
func (r *Resolver) ChatMessage() ChatMessageResolver { return &chatMessageResolver{r} }

// Cluster returns ClusterResolver implementation.
func (r *Resolver) Cluster() ClusterResolver { return &clusterResolver{r} }

// ClusterCache returns ClusterCacheResolver implementation.
func (r *Resolver) ClusterCache() ClusterCacheResolver { return &clusterCacheResolver{r} }

// ClusterCachedKind returns ClusterCachedKindResolver implementation.
func (r *Resolver) ClusterCachedKind() ClusterCachedKindResolver {
	return &clusterCachedKindResolver{r}
}

// ClusterCachedKindSpec returns ClusterCachedKindSpecResolver implementation.
func (r *Resolver) ClusterCachedKindSpec() ClusterCachedKindSpecResolver {
	return &clusterCachedKindSpecResolver{r}
}

// ClusterPrincipal returns ClusterPrincipalResolver implementation.
func (r *Resolver) ClusterPrincipal() ClusterPrincipalResolver { return &clusterPrincipalResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// ToolCall returns ToolCallResolver implementation.
func (r *Resolver) ToolCall() ToolCallResolver { return &toolCallResolver{r} }

type (
	chatMessageResolver           struct{ *Resolver }
	clusterResolver               struct{ *Resolver }
	clusterCacheResolver          struct{ *Resolver }
	clusterCachedKindResolver     struct{ *Resolver }
	clusterCachedKindSpecResolver struct{ *Resolver }
	clusterPrincipalResolver      struct{ *Resolver }
	mutationResolver              struct{ *Resolver }
	queryResolver                 struct{ *Resolver }
	subscriptionResolver          struct{ *Resolver }
	toolCallResolver              struct{ *Resolver }
)
