// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/kstackhq/kstack/sidecar/internal/lib/apimeta"
	"github.com/kstackhq/kstack/sidecar/internal/llm"
	"github.com/kstackhq/kstack/sidecar/internal/run/permissions"
	"github.com/kstackhq/kstack/sidecar/internal/services/memory"
	"github.com/kstackhq/kstack/sidecar/internal/services/settings"
)

// The connecting principal's effective RBAC in one namespace (live
// SelfSubjectRulesReview). Namespace-scoped (the API has no all-namespaces form)
// and point-in-time — for UI/debugging, not authoritative for access decisions.
type ClusterPermissions struct {
	// The namespace these rules were evaluated for.
	Namespace string `json:"namespace"`
	// Allowed resource rules (verbs × apiGroups × resources).
	ResourceRules []*ResourceRule `json:"resourceRules"`
	// Allowed non-resource rules (verbs × URLs), e.g. /healthz.
	NonResourceRules []*NonResourceRule `json:"nonResourceRules"`
	// True if some authorizers couldn't be evaluated, so the rule set may be incomplete.
	Incomplete bool `json:"incomplete"`
}

type MemorySaveInput struct {
	// The memory to rewrite. Null creates one.
	ID *memory.MemoryID `json:"id,omitempty"`
	// The cluster it is for. Null is every cluster.
	ClusterID *apimeta.ClusterID `json:"clusterID,omitempty"`
	Name      string             `json:"name"`
	Body      string             `json:"body"`
}

// A model the sidecar can answer with.
type Model struct {
	Provider *Provider `json:"provider"`
	ID       string    `json:"id"`
	Label    string    `json:"label"`
	// The effort levels this model accepts, in the provider's own words, least to most. Empty when it has no such knob.
	Efforts []string `json:"efforts"`
	// The level a picker starts on. Empty when `efforts` is.
	DefaultEffort string `json:"defaultEffort"`
}

type Mutation struct {
}

// A non-resource RBAC rule: the verbs the principal may use against non-resource URLs (e.g. /healthz).
type NonResourceRule struct {
	Verbs           []string `json:"verbs"`
	NonResourceUrls []string `json:"nonResourceUrls"`
}

// A rule to add; every string is a pattern but `group`, and empty matches anything. A `namespace` of `[cluster]` is cluster-scoped objects alone.
type PermissionRuleInput struct {
	Effect    permissions.Effect `json:"effect"`
	Class     permissions.Class  `json:"class"`
	Context   string             `json:"context"`
	Namespace string             `json:"namespace"`
	Verb      string             `json:"verb"`
	Group     string             `json:"group"`
	Kind      string             `json:"kind"`
}

// The modes and rules sandboxed commands' cluster writes are decided by.
type PermissionSettings struct {
	// The mode of a context nothing else names.
	DefaultMode permissions.Mode `json:"defaultMode"`
	// Each known context's mode, by context.
	Contexts []*settings.ContextModeState `json:"contexts"`
	// The user's always rules.
	Rules []*permissions.Rule `json:"rules"`
	// The writes that always ask, in words.
	Destructive []string `json:"destructive"`
	// The settings fields the file holds a value of that Kstack cannot read, by key: `permissions.defaultMode`, `permissions.modes`, `permissions.rules`.
	Held []string `json:"held"`
}

// A provider the sidecar can send a turn to.
type Provider struct {
	// Stable for the life of the app: what `chatSend` and a stored message name.
	ID string `json:"id"`
	// What a picker shows as the group heading.
	Label string `json:"label"`
	// The dialect this provider speaks. Null on a provider the sidecar no longer holds — a stored message's, labelled by its id — since nothing but the id is known of it.
	LlmDialect *llm.Dialect `json:"llmDialect,omitempty"`
}

type Query struct {
}

// A resource-scoped RBAC rule: the verbs the principal may use on the given apiGroups/resources (optionally narrowed to named instances).
type ResourceRule struct {
	Verbs     []string `json:"verbs"`
	APIGroups []string `json:"apiGroups"`
	Resources []string `json:"resources"`
	// Specific resource names this rule is restricted to; empty means all.
	ResourceNames []string `json:"resourceNames"`
}

// One executable the sandbox probe checks, as the last probe found it.
type SandboxExecutable struct {
	// The executable's name. User text for a registered one: draw it through VisibleText.
	Name string `json:"name"`
	// What the probe runs, split on whitespace and never through a shell.
	Invocation string `json:"invocation"`
	// Registered by the user in Settings, not on the curated list.
	Registered bool `json:"registered"`
	// Whether a probe has run it; false for an executable listed since the last probe, whose `error` says so.
	Probed bool `json:"probed"`
	// The binary on the sandbox's PATH; empty when none. Draw it through VisibleText.
	Resolved string `json:"resolved"`
	// Under a version manager's shims folder.
	Shim bool `json:"shim"`
	// The binary behind a shim; empty when unknown.
	Target string `json:"target"`
	// The invocation exited 0.
	Ok bool `json:"ok"`
	// The first non-empty line of its output, redacted. The executable's own text: draw it through VisibleText.
	Version string `json:"version"`
	// Why it did not run or did not pass: Bash's first line, `not found on the sandbox's PATH`, `could not start: …` or `not probed yet`; empty when ok.
	Error string `json:"error"`
}

// The executable probe as a watcher sees it.
type SandboxExecutablesReport struct {
	// A probe is running; its reports land in `executables` when it ends.
	Probing bool `json:"probing"`
	// How many probes have started since the sidecar did. A gauge keeps its latest value alone, so a probe's start and end can arrive as one frame; a watcher that asked for a probe knows it started once this moved.
	Probes int `json:"probes"`
	// Every executable the probe checks, the curated ones then the user's, as the last probe found each. Empty on a machine with no sandbox.
	Executables []*SandboxExecutable `json:"executables"`
}

// One folder a sandboxed command may read, or read and write.
type SandboxFolder struct {
	// The rule's id.
	ID string `json:"id"`
	// The folder, absolute and resolved. User text: draw it through VisibleText.
	Path  string `json:"path"`
	Write bool   `json:"write"`
	// Why the folder fails its check now, so no run takes it; null when it passes.
	Refused *string `json:"refused,omitempty"`
}

// The folders granted, and what no grant opens.
type SandboxFolders struct {
	// The always grants.
	Always []*SandboxFolder `json:"always"`
	// The chat's own grants, for their refused reasons; empty when no chat was named.
	Chat []*SandboxFolder `json:"chat"`
	// The denied-always list for this machine, with ~ expanded, read-only.
	Never []string `json:"never"`
	// The folders a read grant of which draws the wide warning, resolved: the home, each folder over it, and /Volumes on macOS.
	Wide []string `json:"wide"`
	// Whether the file's rules cannot be read, which refuses every always grant and revoke until the file is fixed or what Kstack cannot read is discarded.
	RulesHeld bool `json:"rulesHeld"`
}

// One folder of the user's PATH, and what the sandbox does with it.
type SandboxPathEntry struct {
	// The folder as the shell gave it.
	Dir string `json:"dir"`
	// The folder dir resolved to when its state was set; the one the sandbox reads.
	Target string            `json:"target"`
	State  SandboxPathState  `json:"state"`
	Source SandboxPathSource `json:"source"`
	// Whether target was writable by a group other than an administrators' one, so others in it can add programs to it.
	Shared bool `json:"shared"`
}

type Subscription struct {
}

// How long a folder grant lasts.
type GrantDuration string

const (
	// For one chat: a rule of the chat's, gone with it.
	GrantDurationChat GrantDuration = "Chat"
	// For every chat: a rule in the settings file.
	GrantDurationAlways GrantDuration = "Always"
)

var AllGrantDuration = []GrantDuration{
	GrantDurationChat,
	GrantDurationAlways,
}

func (e GrantDuration) IsValid() bool {
	switch e {
	case GrantDurationChat, GrantDurationAlways:
		return true
	}
	return false
}

func (e GrantDuration) String() string {
	return string(e)
}

func (e *GrantDuration) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GrantDuration(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GrantDuration", str)
	}
	return nil
}

func (e GrantDuration) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GrantDuration) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GrantDuration) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Whose decision a PATH entry's state is.
type SandboxPathSource string

const (
	// Kstack's, when it read the login shell's PATH.
	SandboxPathSourceShell SandboxPathSource = "Shell"
	// The user's, by Include or Remove.
	SandboxPathSourceUser SandboxPathSource = "User"
)

var AllSandboxPathSource = []SandboxPathSource{
	SandboxPathSourceShell,
	SandboxPathSourceUser,
}

func (e SandboxPathSource) IsValid() bool {
	switch e {
	case SandboxPathSourceShell, SandboxPathSourceUser:
		return true
	}
	return false
}

func (e SandboxPathSource) String() string {
	return string(e)
}

func (e *SandboxPathSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SandboxPathSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SandboxPathSource", str)
	}
	return nil
}

func (e SandboxPathSource) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SandboxPathSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SandboxPathSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// What the sandbox does with one folder of the user's PATH.
type SandboxPathState string

const (
	// On the sandbox's PATH and readable in it.
	SandboxPathStateAdopted SandboxPathState = "Adopted"
	// Listed by the shell and waiting for the user: adopting it would open more to commands, or its group can add programs to it.
	SandboxPathStatePending SandboxPathState = "Pending"
	// Removed by the user, and kept so a launch does not adopt it again.
	SandboxPathStateGone SandboxPathState = "Gone"
)

var AllSandboxPathState = []SandboxPathState{
	SandboxPathStateAdopted,
	SandboxPathStatePending,
	SandboxPathStateGone,
}

func (e SandboxPathState) IsValid() bool {
	switch e {
	case SandboxPathStateAdopted, SandboxPathStatePending, SandboxPathStateGone:
		return true
	}
	return false
}

func (e SandboxPathState) String() string {
	return string(e)
}

func (e *SandboxPathState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SandboxPathState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SandboxPathState", str)
	}
	return nil
}

func (e SandboxPathState) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SandboxPathState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SandboxPathState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
