// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/kstackhq/kstack/sidecar/internal/apimeta"
	"github.com/kstackhq/kstack/sidecar/internal/llm"
	"github.com/kstackhq/kstack/sidecar/internal/memorysvc"
	"github.com/kstackhq/kstack/sidecar/internal/permissions"
	"github.com/kstackhq/kstack/sidecar/internal/securityconfig"
)

// The connecting principal's effective RBAC in one namespace (live
// SelfSubjectRulesReview). Namespace-scoped (the API has no all-namespaces form)
// and point-in-time — for UI/debugging, not authoritative for access decisions.
type ClusterPermissions struct {
	// The namespace these rules were evaluated for.
	Namespace string `json:"namespace"`
	// Allowed resource rules (verbs × apiGroups × resources).
	ResourceRules []*ResourceRule `json:"resourceRules"`
	// Allowed non-resource rules (verbs × URLs), e.g. /healthz.
	NonResourceRules []*NonResourceRule `json:"nonResourceRules"`
	// True if some authorizers couldn't be evaluated, so the rule set may be incomplete.
	Incomplete bool `json:"incomplete"`
}

type MemorySaveInput struct {
	// The memory to rewrite. Null creates one.
	ID *memorysvc.MemoryID `json:"id,omitempty"`
	// The cluster it is for. Null is every cluster.
	ClusterID *apimeta.ClusterID `json:"clusterID,omitempty"`
	Name      string             `json:"name"`
	Body      string             `json:"body"`
}

// A model the sidecar can answer with.
type Model struct {
	Provider *Provider `json:"provider"`
	ID       string    `json:"id"`
	Label    string    `json:"label"`
	// The effort levels this model accepts, in the provider's own words, least to most. Empty when it has no such knob.
	Efforts []string `json:"efforts"`
	// The level a picker starts on. Empty when `efforts` is.
	DefaultEffort string `json:"defaultEffort"`
}

type Mutation struct {
}

// A non-resource RBAC rule: the verbs the principal may use against non-resource URLs (e.g. /healthz).
type NonResourceRule struct {
	Verbs           []string `json:"verbs"`
	NonResourceUrls []string `json:"nonResourceUrls"`
}

// A rule to add; every string is a pattern but `group`, and empty matches anything.
type PermissionRuleInput struct {
	Effect    permissions.Effect `json:"effect"`
	Class     permissions.Class  `json:"class"`
	Context   string             `json:"context"`
	Namespace string             `json:"namespace"`
	Verb      string             `json:"verb"`
	Group     string             `json:"group"`
	Kind      string             `json:"kind"`
}

// The modes and rules sandboxed commands' cluster writes are decided by.
type PermissionSettings struct {
	// The mode of a context nothing else names.
	DefaultMode permissions.Mode `json:"defaultMode"`
	// Each known context's mode, by context.
	Contexts []*securityconfig.ContextModeState `json:"contexts"`
	// The user's always rules.
	Rules []*permissions.Rule `json:"rules"`
	// The writes that always ask, in words.
	Destructive []string `json:"destructive"`
	// The settings fields the file holds a value of that Kstack cannot read: `defaultMode`, `modes`, `rules`.
	Held []string `json:"held"`
}

// A provider the sidecar can send a turn to.
type Provider struct {
	// Stable for the life of the app: what `chatSend` and a stored message name.
	ID string `json:"id"`
	// What a picker shows as the group heading.
	Label string `json:"label"`
	// The dialect this provider speaks. Null on a provider the sidecar no longer holds — a stored message's, labelled by its id — since nothing but the id is known of it.
	LlmDialect *llm.Dialect `json:"llmDialect,omitempty"`
}

type Query struct {
}

// A resource-scoped RBAC rule: the verbs the principal may use on the given apiGroups/resources (optionally narrowed to named instances).
type ResourceRule struct {
	Verbs     []string `json:"verbs"`
	APIGroups []string `json:"apiGroups"`
	Resources []string `json:"resources"`
	// Specific resource names this rule is restricted to; empty means all.
	ResourceNames []string `json:"resourceNames"`
}

// One folder of the user's PATH, and what the sandbox does with it.
type SandboxPathEntry struct {
	// The folder as the shell gave it.
	Dir string `json:"dir"`
	// The folder dir resolved to when its state was set; the one the sandbox reads.
	Target string            `json:"target"`
	State  SandboxPathState  `json:"state"`
	Source SandboxPathSource `json:"source"`
	// Whether target was writable by a group other than an administrators' one, so others in it can add programs to it.
	Shared bool `json:"shared"`
}

type Subscription struct {
}

// Whose decision a PATH entry's state is.
type SandboxPathSource string

const (
	// Kstack's, when it read the login shell's PATH.
	SandboxPathSourceShell SandboxPathSource = "Shell"
	// The user's, by Include or Remove.
	SandboxPathSourceUser SandboxPathSource = "User"
)

var AllSandboxPathSource = []SandboxPathSource{
	SandboxPathSourceShell,
	SandboxPathSourceUser,
}

func (e SandboxPathSource) IsValid() bool {
	switch e {
	case SandboxPathSourceShell, SandboxPathSourceUser:
		return true
	}
	return false
}

func (e SandboxPathSource) String() string {
	return string(e)
}

func (e *SandboxPathSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SandboxPathSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SandboxPathSource", str)
	}
	return nil
}

func (e SandboxPathSource) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SandboxPathSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SandboxPathSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// What the sandbox does with one folder of the user's PATH.
type SandboxPathState string

const (
	// On the sandbox's PATH and readable in it.
	SandboxPathStateAdopted SandboxPathState = "Adopted"
	// Listed by the shell and waiting for the user: adopting it would open more to commands, or its group can add programs to it.
	SandboxPathStatePending SandboxPathState = "Pending"
	// Removed by the user, and kept so a launch does not adopt it again.
	SandboxPathStateGone SandboxPathState = "Gone"
)

var AllSandboxPathState = []SandboxPathState{
	SandboxPathStateAdopted,
	SandboxPathStatePending,
	SandboxPathStateGone,
}

func (e SandboxPathState) IsValid() bool {
	switch e {
	case SandboxPathStateAdopted, SandboxPathStatePending, SandboxPathStateGone:
		return true
	}
	return false
}

func (e SandboxPathState) String() string {
	return string(e)
}

func (e *SandboxPathState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SandboxPathState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SandboxPathState", str)
	}
	return nil
}

func (e SandboxPathState) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SandboxPathState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SandboxPathState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
