// Shared proto contract for host(Rust) <-> sidecar(Go) gRPC resync control channel.
//
// This file is the single source of truth for the PokeService wire format,
// consumed by both the Go sidecar (via protoc, see sidecar/grpc/pokepb) and
// the Rust host (via tonic-build, see src-tauri/build.rs). It deliberately
// sits at the repo root alongside auth.proto.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: poke.proto

package pokepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PokeService_Poke_FullMethodName = "/poke.PokeService/Poke"
)

// PokeServiceClient is the client API for PokeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PokeService is the host-internal resync channel. The native host calls Poke
// when the OS resumes from sleep or the network becomes reachable again; the
// sidecar broadcasts a SourceHost resync signal to every in-process subscriber
// (the kubeconfig watch and the per-cluster Kubernetes sync), waking long-lived
// network connections that may have gone stale. It rides the same
// socket as GraphQL and the other gRPC services (h2c multiplexing) and is
// consumed only by the native host, never the webview.
//
// The sidecar also has a built-in wall-clock gap detector that fires the same
// resync internally, so Poke is an accelerator for an explicit host wake event,
// not the only path.
type PokeServiceClient interface {
	// Poke broadcasts a resync signal to every in-process subscriber. Unary and
	// best-effort: it never blocks and returns as soon as the signal is queued.
	Poke(ctx context.Context, in *PokeRequest, opts ...grpc.CallOption) (*PokeResponse, error)
}

type pokeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPokeServiceClient(cc grpc.ClientConnInterface) PokeServiceClient {
	return &pokeServiceClient{cc}
}

func (c *pokeServiceClient) Poke(ctx context.Context, in *PokeRequest, opts ...grpc.CallOption) (*PokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PokeResponse)
	err := c.cc.Invoke(ctx, PokeService_Poke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokeServiceServer is the server API for PokeService service.
// All implementations must embed UnimplementedPokeServiceServer
// for forward compatibility.
//
// PokeService is the host-internal resync channel. The native host calls Poke
// when the OS resumes from sleep or the network becomes reachable again; the
// sidecar broadcasts a SourceHost resync signal to every in-process subscriber
// (the kubeconfig watch and the per-cluster Kubernetes sync), waking long-lived
// network connections that may have gone stale. It rides the same
// socket as GraphQL and the other gRPC services (h2c multiplexing) and is
// consumed only by the native host, never the webview.
//
// The sidecar also has a built-in wall-clock gap detector that fires the same
// resync internally, so Poke is an accelerator for an explicit host wake event,
// not the only path.
type PokeServiceServer interface {
	// Poke broadcasts a resync signal to every in-process subscriber. Unary and
	// best-effort: it never blocks and returns as soon as the signal is queued.
	Poke(context.Context, *PokeRequest) (*PokeResponse, error)
	mustEmbedUnimplementedPokeServiceServer()
}

// UnimplementedPokeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPokeServiceServer struct{}

func (UnimplementedPokeServiceServer) Poke(context.Context, *PokeRequest) (*PokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Poke not implemented")
}
func (UnimplementedPokeServiceServer) mustEmbedUnimplementedPokeServiceServer() {}
func (UnimplementedPokeServiceServer) testEmbeddedByValue()                     {}

// UnsafePokeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokeServiceServer will
// result in compilation errors.
type UnsafePokeServiceServer interface {
	mustEmbedUnimplementedPokeServiceServer()
}

func RegisterPokeServiceServer(s grpc.ServiceRegistrar, srv PokeServiceServer) {
	// If the following call panics, it indicates UnimplementedPokeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PokeService_ServiceDesc, srv)
}

func _PokeService_Poke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokeServiceServer).Poke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokeService_Poke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokeServiceServer).Poke(ctx, req.(*PokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PokeService_ServiceDesc is the grpc.ServiceDesc for PokeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PokeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poke.PokeService",
	HandlerType: (*PokeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Poke",
			Handler:    _PokeService_Poke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poke.proto",
}
